// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qvrhegtdstcfpbhjvwsk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF2cmhlZ3Rkc3RjZnBiaGp2d3NrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyOTg1MDAsImV4cCI6MjA2MDg3NDUwMH0.xNyrF3RYNuRC6VjXRYQKo1p7Hrgj5LuzVBXBXz7zKFs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);